#!/bin/bash

ROOT_PATH=$(cd $(dirname $0) && pwd);

. $ROOT_PATH/include/backup.conf

# coloring output
BOLD="$(tput bold)"
UNDERLINE="$(tput smul)"
STANDOUT="$(tput smso)"
NONE="$(tput sgr0)"
BLACK="$(tput setaf 0)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
PURPLE="$(tput setaf 5)"
CYAN="$(tput setaf 6)"
WHITE="$(tput setaf 7)"

print() {
    if [ $# -gt 1 ]; then
        echo $2$1$NONE
        tput sgr0
    else
        echo $1
    fi
}